# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='precio_galon',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterField(
            model_name='precio_galon',
            name='fecha',
            field=models.DateField(unique=True),
        ),
    ]
