# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0003_camion_chofer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camion',
            options={'ordering': ['ficha'], 'verbose_name_plural': 'camiones'},
        ),
        migrations.AlterModelOptions(
            name='chofer',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'choferes'},
        ),
        migrations.AddField(
            model_name='camion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chofer',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
