# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 02:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0004_auto_20170415_0203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Precio_Galon',
            new_name='PrecioGalon',
        ),
    ]
