# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descuento', models.IntegerField()),
                ('dias_credito', models.IntegerField()),
                ('documento', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('telefono1', models.CharField(blank=True, max_length=20)),
                ('telefono2', models.CharField(blank=True, max_length=20)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('referencia', models.CharField(blank=True, max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clientes.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='clientes.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Sectores',
                'ordering': ['-descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('documento', models.CharField(blank=True, max_length=20)),
                ('salario', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('meta_galones', models.IntegerField(default=0)),
                ('tipo_comision', models.CharField(blank=True, choices=[('p', 'Porcentual'), ('v', 'Variable')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Vendedores',
            },
        ),
        migrations.AddField(
            model_name='contacto',
            name='tipo_contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clientes.TipoContacto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='clientes.Sector'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='clientes.Vendedor'),
        ),
    ]
