# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=20)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('meta_galones', models.IntegerField()),
                ('tipo_comision', models.CharField(choices=[('p', 'Porcentual'), ('v', 'Variable')], max_length=1)),
            ],
        ),
    ]
