# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20170425_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
