# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20170408_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['-descripcion']},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['-descripcion'], 'verbose_name_plural': 'Sectores'},
        ),
        migrations.AlterModelOptions(
            name='tipocontacto',
            options={'ordering': ['-descripcion']},
        ),
    ]
