# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20170408_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['descripcion']},
        ),
        migrations.AlterModelOptions(
            name='tipocontacto',
            options={'ordering': ['descripcion']},
        ),
    ]
