# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20170427_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
