# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('params', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('fecha', models.DateField()),
                ('condicion', models.IntegerField(choices=[(1, 'contado'), (2, 'crédito')])),
                ('galones', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('precio_galon', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('fecha_vence', models.DateField()),
                ('referencia', models.CharField(blank=True, max_length=30)),
                ('numero_fiscal', models.CharField(blank=True, max_length=50)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='params.Camion')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='params.Chofer')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='clientes.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='SecuenciaFacturas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
