# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cliente', models.CharField(max_length=100)),
                ('galones', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('condicion', models.IntegerField(choices=[(1, 'Contado'), (2, 'Crédito')])),
                ('fiscal', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='factura',
            name='condicion',
            field=models.IntegerField(choices=[(1, 'Contado'), (2, 'Crédito')]),
        ),
    ]
