# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0001_initial'),
        ('facturas', '0002_auto_20170502_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuenciaFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='newfactura',
            name='camion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='params.Camion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newfactura',
            name='chofer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='params.Chofer'),
            preserve_default=False,
        ),
    ]
