# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('params', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha', models.DateField()),
                ('condicion', models.IntegerField(choices=[(1, 'Contado'), (2, 'Crédito')])),
                ('cliente', models.CharField(max_length=100)),
                ('galones', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('precio_galon', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('valor_fiscal', models.BooleanField(default=False)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='params.Camion')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='params.Chofer')),
            ],
            options={
                'ordering': ('-fecha',),
            },
        ),
    ]
