# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawfactura',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
